### ISSUE TITLE
README nees more content

### ISSUE THREAD

**Issue by larubbio** [llavoie/nms-sql#1]

**Comment by llavoie** [comment]
@larubbio Issue title needs better spelling.

**Comment by larubbio** [comment]
You aren't going to develop a community if you are so hostile to
contributions.

**Comment by larubbio** [comment]
![me_fail_english_demotivator_by_purplephoneixstar-d4nw89m](https://cloud.githubusercontent.com/assets/51527/12825676/5b93a7da-cb2c-11e5-8d05-58f7c7a4354d.jpg)
